"""add_telegram_chat_id

Revision ID: 0275f98d5374
Revises: d1ac99bfaba7
Create Date: 2026-02-08 15:56:04.962465

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0275f98d5374'
down_revision: Union[str, Sequence[str], None] = 'd1ac99bfaba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
