"""Added skills

Revision ID: 31031020e2a4
Revises: 5075f9a0f5ea
Create Date: 2026-01-10 18:22:51.711955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '31031020e2a4'
down_revision: Union[str, Sequence[str], None] = '5075f9a0f5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skills_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('skills_text')
        batch_op.drop_column('study_year')

    # ### end Alembic commands ###
