"""Added categories with batch mode

Revision ID: 5075f9a0f5ea
Revises: fff6572fce47
Create Date: 2026-01-07 18:43:57.734561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "5075f9a0f5ea"
down_revision: Union[str, Sequence[str], None] = "fff6572fce47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, "categories", ["preferred_category_id"], ["id"]
        )
        batch_op.drop_column("preferred_category")

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_teams_category"))
        batch_op.drop_constraint(batch_op.f("uix_team_name_category"), type_="unique")
        batch_op.create_unique_constraint(
            "uix_team_name_category", ["team_name", "category_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_teams_category_id"), ["category_id"], unique=False
        )
        batch_op.create_foreign_key(None, "categories", ["category_id"], ["id"])
        batch_op.drop_column("category")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category", sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_teams_category_id"))
        batch_op.drop_constraint("uix_team_name_category", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uix_team_name_category"), ["team_name", "category"]
        )
        batch_op.create_index(
            batch_op.f("ix_teams_category"), ["category"], unique=False
        )
        batch_op.drop_column("category_id")

    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("preferred_category", sa.VARCHAR(), nullable=True)
        )

    # ### end Alembic commands ###
