"""a_lot_of_features

Revision ID: c38ff15d6405
Revises: fb82e889cd57
Create Date: 2026-02-06 18:07:32.782632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "c38ff15d6405"
down_revision: Union[str, Sequence[str], None] = "fb82e889cd57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("INVITE", "REQUEST", name="invitationtype"), nullable=False
        ),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACCEPTED", "DECLINED", "CANCELED", name="invitationstatus"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_invitations")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        op.execute(
            "ALTER TABLE categories DROP CONSTRAINT IF EXISTS uq_categories_name"
        )
        op.execute(
            "ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key"
        )
        try:
            batch_op.drop_index(batch_op.f("ix_categories_name"))
        except Exception:
            pass
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=True)

    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_category_change", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(sa.Column("last_bio_update", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "skills_embedding",
                pgvector.sqlalchemy.vector.VECTOR(dim=768),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("last_skills_update", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column(
            "participation_format",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum("ONLINE", "OFFLINE", name="participationformat"),
            existing_nullable=False,
        )
        batch_op.create_index(
            "ix_participants_skills_embedding",
            ["skills_embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"skills_embedding": "vector_cosine_ops"},
        )

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_category_change", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("universities", schema=None) as batch_op:
        # tolerate system-generated constraint name or missing constraint
        op.execute(
            "ALTER TABLE universities DROP CONSTRAINT IF EXISTS uq_universities_name"
        )
        op.execute(
            "ALTER TABLE universities DROP CONSTRAINT IF EXISTS universities_name_key"
        )
        try:
            batch_op.drop_index(batch_op.f("ix_universities_name"))
        except Exception:
            pass
        batch_op.create_index(batch_op.f("ix_universities_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universities_name"))
        batch_op.create_index(
            batch_op.f("ix_universities_name"), ["name"], unique=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_universities_name"),
            ["name"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_column("last_category_change")

    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_participants_skills_embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"skills_embedding": "vector_cosine_ops"},
        )
        batch_op.alter_column(
            "participation_format",
            existing_type=sa.Enum("ONLINE", "OFFLINE", name="participationformat"),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )
        batch_op.drop_column("last_skills_update")
        batch_op.drop_column("skills_embedding")
        batch_op.drop_column("last_bio_update")
        batch_op.drop_column("bio")
        batch_op.drop_column("last_category_change")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("uq_categories_name"),
            ["name"],
            postgresql_nulls_not_distinct=False,
        )

    op.drop_table("team_invitations")
    # ### end Alembic commands ###
