"""add_telegram_chat_id_to_participants

Revision ID: d1ac99bfaba7
Revises: 0d58b363be2b
Create Date: 2026-02-08 14:26:11.559951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ac99bfaba7'
down_revision: Union[str, Sequence[str], None] = '0d58b363be2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_participants_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_telegram_chat_id'))
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
