"""Make study fields optional

Revision ID: fb82e889cd57
Revises: b567d301d5bc
Create Date: 2026-01-19 16:10:45.898726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb82e889cd57"
down_revision: Union[str, Sequence[str], None] = "b567d301d5bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_student", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.alter_column("study_year", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "university_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.alter_column(
            "university_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("study_year", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("is_student")

    # ### end Alembic commands ###
